from snakemake.utils import min_version
min_version("7.0")

configfile: "config/config.yaml"
include: "rules/common.smk"
include: "rules/sumstats.smk"
include: "rules/fastq.smk"
include: "rules/reference.smk"
include: "rules/mappability.smk"

setup_curlrc()
onerror: cleanup_curlrc()
onsuccess: cleanup_curlrc()


if config['sentieon']:
    include: "rules/sentieon.smk"
else:
    include: "rules/fastq2bam.smk"
    if config['intervals']:
        include: "rules/bam2vcf_gatk_intervals.smk"
        include: "rules/intervals.smk"
    else:
        include: "rules/bam2vcf_gatk.smk"

if config['cov_filter']:
    include: "rules/cov_filter.smk"

rule all:
    input:
        get_output()
    default_target: True
